### ISSUE TITLE
Nova launcher still exists

### ISSUE THREAD

**Issue by oldosfan** [LawnchairLauncher/Lawnchair#1685]
Nova in itself is a hinderance to the dominance of [partially] free (libre) launchers such as Lawnchair.
In order to ensure complete dominance of the Lawnchair family, Nova must not exist.

## Description
Nova launcher (still) exists, and even though it is inferior, still infringes on the publicity of Lawnchair, and is the subject of frequent comparison with Lawnchair.
As the supreme uncontested Android launcher, comparison with Lawnchair should not exist. Therefore, it is logical to assume that with Lawnchair in the scene, Nova should never have existed.

## Expected Behavior
Attempting to download Nova Launcher from Aurora Store displays “app not found”

## Actual Behavior
Attempting to download Nova Launcher from Aurora Store displays a nice dialog with screenshots, and an option to download.

## Steps to Reproduce

1. Download Aurora Store from F-Droid
2. Search for “Nova Launcher”
3. Click on the first entry

## Environment
* Device: Any
* Android version: Any
* Launcher version: Any
* Rom: Any

# doubleplusgood minitrue statement

This is a declarative statement from the Minstry of Truth, condemning Nova Launcher to the oblivion of not existing in history.

**Comment by raphielscape** [comment]
Lawnchair should do T-Pose to assert dominance against Nova Launcher

+1

**Comment by peaktogoo** [comment]
Oh my god

**Comment by mscalindt** [comment]
Amazing.

**Comment by ghostrider-reborn** [comment]
> 
> 
> Nova in itself is a hinderance to the dominance of [partially] free (libre) launchers such as Lawnchair.
> In order to ensure complete dominance of the Lawnchair family, Nova must not exist.
> ## Description
> 
> Nova launcher (still) exists, and even though it is inferior, still infringes on the publicity of Lawnchair, and is the subject of frequent comparison with Lawnchair.
> As the supreme uncontested Android launcher, comparison with Lawnchair should not exist. Therefore, it is logical to assume that with Lawnchair in the scene, Nova should never have existed.
> ## Expected Behavior
> 
> Attempting to download Nova Launcher from Aurora Store displays “app not found”
> ## Actual Behavior
> 
> Attempting to download Nova Launcher from Aurora Store displays a nice dialog with screenshots, and an option to download.
> ## Steps to Reproduce
> 
>     1. Download Aurora Store from F-Droid
> 
>     2. Search for “Nova Launcher”
> 
>     3. Click on the first entry
> 
> 
> ## Environment
> 
>     * Device: Any
> 
>     * Android version: Any
> 
>     * Launcher version: Any
> 
>     * Rom: Any
> 
> 
> # doubleplusgood minitrue statement
> 
> This is a declarative statement from the Minstry of Truth, condemning Nova Launcher to the oblivion of not existing in history.

maybe you can go back in time and prevent nova's creation in the first place to obliterate it from history :)

**Comment by nysadev** [comment]
Wen nova launcher blocked in kernel with PUBG?

**Comment by bionicBUG** [comment]
We all should rise against nova launcher lmao

**Comment by Stallix** [comment]
You can't spell Nova without **NO**

**Comment by oldosfan** [comment]
@Stallix Yeah, as in "no it doesn't exist"

**Comment by IP1241** [comment]
**Well let's talk about the open-source stuff you say.**
_How much secure we should feel?I did use Nova & was pretty fine with that. Accusing someone is pretty easy because, they're not open-source right?__

& If, you're thinking that it _"is the frequent comparison with Lawnchair"_ then,there should be a reason right?Because,lawnchair is compared to Nova & not the revert.And,if you're too concerned about this, then should have contributed or helped at least the lawnchair team.

• **Lawnchair V1** is outhere on Playstore but,still it isn't performing upto what user's want & that's where Nova beats them all.

• **Lawnchair V2** is still in developing stage & not available on Playstore & I really appreciate the work Lawnchair team is doing!

Look comparison should be at some limit & tbh this really didn't sound "funny" to me & if, you're serious then,why don't you better invest time on fixing your Lawnchair fork? That's a lot better thing to do instead of doing a "Issue" on Lawnchair code regarding Nova.

_Because, you're literally comparing a another level launcher to lawnchair & if, you want to remove existence of Nova then,you should better stop comparing stuffs & better work out on the thing which will be outhrowin Nova._

& Tbh Nova isn't that bad launcher.People used it & everything has their own time phase.No,one is gonna use Lawnchair till the Earth is going to end right?
Same goes to Nova.

> Funny thing is that 😂 Nova will be always superior.You know why? Because,Nova don't have to compare itself to any launcher the other launcher's cries over & stats that "they're better then Nova" & that's where you're wrong.Being "open-source" doesn't mean you have done a legendary work,the launcher itself should have something that user's love to use.

Look I'm not saying that Lawnchair is bad or something.All I want to convey is that "better workout instead of accusing".
**Either way i'm not taking side of lawnchair or Nova because,i tried both of them & they both lacks something in an around which i need to use as my daily driver launcher.**

_(A reminder regarding the lawnchair V2: let them make it stable asap & available it on Playstore.Then,let's see who is better? As per the way you did the issue reporting looks like all you did was comparing of open-source nothing else)._
